model_name: TPG

train_batch_size: 64
test_batch_size: 64
num_epochs: 50
patience: 20

lr: 0.001
lr_step: 2
lr_decay: 0.1
schedule_threshold: 0.001
early_stop_lr: 0.000009

weight_decay: 0.0001
device: "cuda:1"
